version: '2'
services:
  formula:
    environment:
      GEENY_APPLICATION_BROKER_SUBSCRIBER_URL: http://subscription-service:1319/v2/application
      GEENY_APPLICATION_ID: LocalApplication
      GEENY_APPLICATION_AUTH_TOKEN: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBsaWNhdGlvbklkIjoiTG9jYWxBcHBsaWNhdGlvbiJ9.Xtvp7carikezp8P5_9kuPS2S9EZyewxmSzaHwXk5scvorhQnCY7jZsus7tlI1OnFgwLxhf2AJrTxoDYATzlYSrqwM2qoXF0TMVR_b-9PcCcL1nhIwEh9Zuc44Vz6W4Cy_eG9bpPV8bls_TwOW8kpYVp4QcCsNJ_rzDr_NXxMV_gH_1NPefe5CdPhbuGGIKBHLvPzAAQOHrKdUoD1-TnyXe4GB14JgwjnWfs8MlV9K_23Z8mrEQKGnhttGjLO8T2UQK_lJOTPnD4KTqLQsj7B02M1upJ4Ghsq1hzzBzhYpakVt-q1UY70U2Sxbtg_SY7kLEssGdkGeLRMWBkuoNxr8Q
    build: .
    depends_on:
      - subscription-service
    ports:
      - "3000:80"
  subscription-service:
    image: geeny/subscription-service-local
    volumes:
      - ./data:/app/data
    ports:
      - "1319:1319"
    environment:
      GEENY_CONSUMER_FOLDER: data
      GEENY_PUBLIC_KEY: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0wA2ai6u3aLIrFaoQ68E
        kxAumxphS2Yfmdwg+wZRj5OTngEEj6TooiIwTr4gpLv80A8dy1mmt73OgCMFXZ5E
        OL/qxOxTUT9nm/k+R49JC09qZZx8Q9xVKClKv1+/LYIWOY1abwzuiHYiuv9dpHvE
        TY01JewGypWGOoPZ5sf6vKHW+E3tgfGrmRwXQnGK2+dRZj49krqHI2zbpOmBhD2k
        lFpYDgzy31ObC7HO9kavaFFvpKr7ZlLeKtM/JLmt2OtAsJ2zMqVF4Vj1K8iwYySk
        73mRQaFX3u1RuyHKVQFklLCH9hQZ2Q6XleFzcSP+vZTkbx8+8TidAodg/W8iCqdA
        FwIDAQAB
        -----END PUBLIC KEY-----

